Update test metric

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Check SQL Assignment Week 6
+name: Check SQL Assignment Week 3
 
 on:
   push:
@@ -36,13 +36,18 @@ jobs:
 
       - name: Execute and Test SQL answers
         run: |
-            # Check if the answers.sql file exists and is not empty
-            if [ -f ./answers.sql ] && [ -s ./answers.sql ]; then
+              # Check if the answers.sql file exists
+              if [ ! -f ./answers.sql ]; then
+                echo "The answers.sql file is missing. Failing the workflow."
+                exit 1
+              fi
+        
+              # Check if the file is truly empty 
+              if ! grep -q '[^[:space:]#]' ./answers.sql; then
+                echo "The answers.sql file is empty or contains only comments. Failing the workflow."
+                exit 1
+              fi
+        
+              # Run the SQL script
               sudo mysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE < ./answers.sql
-            else
-              echo "The answers.sql file is either missing or empty. Failing the workflow."
-              exit 1
-            fi
-  
-      - name: Mark test successful
-        run: echo "All tests passed successfully"
+        
